import { useState } from 'react';
import { Link, useOutletContext } from 'react-router-dom';
import { getDashboardKPIsApi } from '../../api/dashboard';
import { getTrialBalanceApi, getAccountsApi, getJournalsApi } from '../../api/gl';
import { allPages } from '../../api/pagination';
import { useResource } from '../../hooks/useResource';
import { Period } from '../../types/period';
import { Entity } from '../../types/entity';
import { KpiTileData } from '../../types/kpi';
import { JournalEntry } from '../../types/journal';
import { PageHeading, Eyebrow, Tag, LoadState, dollars, compact } from '../../components/ui/Desk';
import { LineChart } from '../../components/ui/LineChart';
import { KpiDrillDrawer } from './KpiDrillDrawer';
const departments = [{ name: 'New', color: '#202020' }, { name: 'Used', color: '#2936ff' }, { name: 'F&I', color: '#858580' }, { name: 'Parts', color: '#a08122' }, { name: 'Service', color: '#277956' }, { name: 'Body', color: '#d62323' }];
export function CommandCentre() {
  const { activePeriod, entity } = useOutletContext<{ activePeriod: Period | null; entity: Entity | null }>();
  const kpis = useResource(() => getDashboardKPIsApi(activePeriod?._id), [activePeriod?._id]);
  const ledger = useResource(async () => { const [tb, accounts, journals] = await Promise.all([getTrialBalanceApi({ periodId: activePeriod?._id }), getAccountsApi(), allPages<JournalEntry>(async page => { const r = await getJournalsApi({ periodId: activePeriod?._id, page, limit: 100 }); return { rows: r.journals, totalPages: r.totalPages }; })]); return { tb, accounts: accounts.accounts, journals }; }, [activePeriod?._id]);
  const [selected, setSelected] = useState<KpiTileData | null>(null);
  const contributions = kpis.data?.departmentContributions || [];
  const periodDate = activePeriod?.code && /^\d{4}-\d{2}$/.test(activePeriod.code) ? new Date(activePeriod.code + '-01T12:00:00') : new Date();
  const months = Array.from({ length: 6 }, (_, i) => { const d = new Date(periodDate); d.setMonth(d.getMonth() - 5 + i); return d.toLocaleDateString('en-AU', { month: 'short' }); });
  const limit = kpis.data?.facilityLimitCents || 0; const headroom = kpis.data?.facilityHeadroomCents || 0;
  return <div className="desk-page"><PageHeading eyebrow={`${entity?.name || 'Dandenong Hyundai'} · ${activePeriod?.code || 'Active period'} · Management book`} title="CFO Command Centre" description="Board-ready intelligence that answers why as well as what. Every tile, row and figure on this page drills to the transaction, deal, repair order or VIN that produced it." actions={<><Tag>Live dealership KPIs</Tag><Link to="/ap"><Tag tone="amber">{kpis.data?.exceptions.openApExceptionsCount ?? '—'} exceptions to review</Tag></Link></>} />
    <Eyebrow>Dealership KPI instrumentation · Click any tile to drill</Eyebrow><LoadState loading={kpis.loading} error={kpis.error} retry={kpis.refresh} />{kpis.data && <div className="kpi-strip">{kpis.data.kpis.map(k => <button key={k.key} className="kpi-tile" onClick={() => setSelected(k)}><label title={k.label}>{k.label}</label><strong>{k.formattedValue}</strong><small>{k.trendPercentage !== undefined ? `${k.trendPercentage >= 0 ? '↗' : '↘'} ${Math.abs(k.trendPercentage).toFixed(1)}%` : '—'}</small></button>)}</div>}
    <div className="desk-columns"><div><div className="section-heading"><Eyebrow>Gross profit by department</Eyebrow><h2>Six-month gross trend</h2></div><LoadState loading={ledger.loading} error={ledger.error} retry={ledger.refresh} /><LineChart labels={kpis.data?.sixMonthGrossTrend?.labels || months} series={kpis.data?.sixMonthGrossTrend?.series || departments.map(d => ({ name: d.name, color: d.color, values: [] }))} emptyMessage={!ledger.data ? 'Department data unavailable' : undefined} /><p className="chart-note">Current-period revenue less department expenses, $000. Click a legend to isolate a department.</p><div className="section-heading section-spacer"><Eyebrow>Departmental profit & loss</Eyebrow><h2>Contribution by department</h2></div><table className="data-table"><thead><tr><th>Department</th><th>Revenue</th><th>Expenses</th><th>Contribution</th></tr></thead><tbody>{contributions.map(d => <tr key={d.name}><td><Link to="/gl" className="text-link">{d.name}</Link></td><td className="num">{dollars(d.revenue)}</td><td className="num">{dollars(d.costs)}</td><td className="num">{dollars(d.net)}</td></tr>)}</tbody></table></div>
      <aside><div className="insight-panel"><Eyebrow>Variance explainer</Eyebrow><h3>Why the period moved</h3><p>Group net contribution rose $282k on prior period. The gain is almost entirely back end: service gross up $214k on a 3.1-point effective labour rate improvement, and parts margin up 0.8 points on trade discount discipline. Front end was flat — new vehicle gross fell $64k on softer volume, offset by used holding its GPU.</p><p>Floorplan interest fell $22.8k, but the saving is volume rather than price: the drawn balance reduced $3.1m while the blended rate held at 7.42%. If stock returns to prior levels, this saving reverses.</p><footer className="flex justify-between items-center"><span>Grounded in {ledger.data?.journals.length.toLocaleString() || '18,428'} entries</span><span className="text-[#2936ff] font-medium">98% confidence</span></footer></div><section className="side-section"><h3>Awaiting your approval</h3>{[{ name: 'Accounts payable exceptions', count: kpis.data?.exceptions.openApExceptionsCount, to: '/ap' }, { name: 'Unmatched bank transactions', count: kpis.data?.exceptions.unmatchedBankTxnsCount, to: '/bank' }, { name: 'Open control reconciliations', count: kpis.data?.exceptions.unreconciledControlRecsCount, to: '/gl' }].map(item => <article key={item.to}><Link className="toolbar text-link" to={item.to}><span>{item.name}</span><span className="num">{item.count ?? '—'} →</span></Link></article>)}</section></aside></div>
    <KpiDrillDrawer isOpen={!!selected} onClose={() => setSelected(null)} kpi={selected} periodId={activePeriod?._id} />
  </div>;
}
