import { useState } from 'react';
import { Link, useOutletContext } from 'react-router-dom';
import { getDashboardKPIsApi } from '../../api/dashboard';
import { getTrialBalanceApi, getAccountsApi, getJournalsApi } from '../../api/gl';
import { allPages } from '../../api/pagination';
import { useResource } from '../../hooks/useResource';
import { Period } from '../../types/period';
import { Entity } from '../../types/entity';
import { KpiTileData } from '../../types/kpi';
import { JournalEntry } from '../../types/journal';
import { PageHeading, Eyebrow, Tag, LoadState, dollars, compact } from '../../components/ui/Desk';
import { LineChart } from '../../components/ui/LineChart';
import { KpiDrillDrawer } from './KpiDrillDrawer';
const departments = [{ name: 'New', color: '#202020' }, { name: 'Used', color: '#2936ff' }, { name: 'F&I', color: '#858580' }, { name: 'Parts', color: '#a08122' }, { name: 'Service', color: '#277956' }, { name: 'Body', color: '#d62323' }];
export function CommandCentre() {
  const { activePeriod, entity } = useOutletContext<{ activePeriod: Period | null; entity: Entity | null }>();
  const kpis = useResource(() => getDashboardKPIsApi(activePeriod?._id), [activePeriod?._id]);
  const ledger = useResource(async () => { const [tb, accounts, journals] = await Promise.all([getTrialBalanceApi({ periodId: activePeriod?._id }), getAccountsApi(), allPages<JournalEntry>(async page => { const r = await getJournalsApi({ periodId: activePeriod?._id, page, limit: 100 }); return { rows: r.journals, totalPages: r.totalPages }; })]); return { tb, accounts: accounts.accounts, journals }; }, [activePeriod?._id]);
  const [selected, setSelected] = useState<KpiTileData | null>(null);
  const contributions = departments.map(dept => { const rows = ledger.data?.tb.accounts.filter(a => a.department === dept.name) || []; const revenue = rows.filter(a => a.type === 'revenue').reduce((s, a) => s + a.totalCreditCents - a.totalDebitCents, 0); const costs = rows.filter(a => a.type === 'expense').reduce((s, a) => s + a.totalDebitCents - a.totalCreditCents, 0); return { ...dept, revenue, costs, net: revenue - costs }; });
  const periodDate = activePeriod?.code && /^\d{4}-\d{2}$/.test(activePeriod.code) ? new Date(activePeriod.code + '-01T12:00:00') : new Date();
  const months = Array.from({ length: 6 }, (_, i) => { const d = new Date(periodDate); d.setMonth(d.getMonth() - 5 + i); return d.toLocaleDateString('en-AU', { month: 'short' }); });
  const limit = kpis.data?.facilityLimitCents || 0; const headroom = kpis.data?.facilityHeadroomCents || 0;
  return <div className="desk-page"><PageHeading eyebrow={`${entity?.name || 'Dandenong Hyundai'} · ${activePeriod?.code || 'Active period'} · Management book`} title="CFO Command Centre" description="Board-ready intelligence that answers why as well as what. Every tile, row and figure on this page drills to the transaction, deal, repair order or VIN that produced it." actions={<><Tag>Live dealership KPIs</Tag><Link to="/ap"><Tag tone="amber">{kpis.data?.exceptions.openApExceptionsCount ?? '—'} exceptions to review</Tag></Link></>} />
    <Eyebrow>Dealership KPI instrumentation · Click any tile to drill</Eyebrow><LoadState loading={kpis.loading} error={kpis.error} retry={kpis.refresh} />{kpis.data && <div className="kpi-strip">{kpis.data.kpis.map(k => <button key={k.key} className="kpi-tile" onClick={() => setSelected(k)}><label title={k.label}>{k.label}</label><strong>{k.formattedValue}</strong><small>{k.trendPercentage !== undefined ? `${k.trendPercentage >= 0 ? '↗' : '↘'} ${Math.abs(k.trendPercentage).toFixed(1)}%` : '—'}</small></button>)}</div>}
    <div className="desk-columns"><div><div className="section-heading"><Eyebrow>Gross profit by department</Eyebrow><h2>Six-month gross trend</h2></div><LoadState loading={ledger.loading} error={ledger.error} retry={ledger.refresh} /><LineChart labels={months} series={contributions.map(d => ({ name: d.name, color: d.color, values: [NaN, NaN, NaN, NaN, NaN, d.net / 100000] }))} emptyMessage={!ledger.data ? 'Department data unavailable' : undefined} /><p className="chart-note">Current-period revenue less department expenses, $000. Only the active period is available from the API; earlier months are not plotted. Click a legend to isolate a department.</p><div className="section-heading section-spacer"><Eyebrow>Departmental profit & loss</Eyebrow><h2>Contribution by department</h2></div><table className="data-table"><thead><tr><th>Department</th><th>Revenue</th><th>Expenses</th><th>Contribution</th></tr></thead><tbody>{contributions.map(d => <tr key={d.name}><td><Link to="/gl" className="text-link">{d.name}</Link></td><td className="num">{ledger.data ? dollars(d.revenue) : '—'}</td><td className="num">{ledger.data ? dollars(d.costs) : '—'}</td><td className="num">{ledger.data ? dollars(d.net) : '—'}</td></tr>)}</tbody></table></div>
      <aside><div className="insight-panel"><Eyebrow>Variance explainer</Eyebrow><h3>Why the period moved</h3><p>{ledger.data ? `The active period records ${dollars(contributions.reduce((s, d) => s + d.net, 0))} of departmental contribution across ${ledger.data.journals.length.toLocaleString()} posted journals.` : 'Loading the active-period ledger.'}</p><p>Prior-period balances and a variance narrative are not supplied by the API. Open the general ledger to inspect the transactions behind the current result.</p><p>{kpis.data ? `Floorplan drawings total ${compact(limit - headroom)}, leaving ${compact(headroom)} of available credit across the ${compact(limit)} facility.` : 'Loading floorplan balances.'}</p><footer>Grounded in {ledger.data?.journals.length.toLocaleString() || '—'} journal entries</footer></div><section className="side-section"><h3>Awaiting your approval</h3>{[{ name: 'Accounts payable exceptions', count: kpis.data?.exceptions.openApExceptionsCount, to: '/ap' }, { name: 'Unmatched bank transactions', count: kpis.data?.exceptions.unmatchedBankTxnsCount, to: '/bank' }, { name: 'Open control reconciliations', count: kpis.data?.exceptions.unreconciledControlRecsCount, to: '/gl' }].map(item => <article key={item.to}><Link className="toolbar text-link" to={item.to}><span>{item.name}</span><span className="num">{item.count ?? '—'} →</span></Link></article>)}</section></aside></div>
    <KpiDrillDrawer isOpen={!!selected} onClose={() => setSelected(null)} kpi={selected} periodId={activePeriod?._id} />
  </div>;
}
