import { useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import { getTrialBalanceApi, getAccountsApi, getJournalsApi, getControlRecsApi } from '../../api/gl';
import { useResource } from '../../hooks/useResource';
import { PageHeading, Tabs, Tag, LoadState, dollars } from '../../components/ui/Desk';
import { Period } from '../../types/period';
import { ControlRec } from '../../types/reconciliation';
import { JournalEntry } from '../../types/journal';
import { AccountDrillDrawer } from './AccountDrillDrawer';
import { ManualJournalModal } from './ManualJournalModal';
import { ControlRecModal } from './ControlRecModal';
import { EvidencePackModal } from './EvidencePackModal';
import { Modal } from '../../components/ui/Modal';

export function GlPage() {
  const { activePeriod } = useOutletContext<{activePeriod:Period|null}>();
  const { data,loading,error,refresh }=useResource(async()=>{const [tb,accounts,journals,recs]=await Promise.all([getTrialBalanceApi({periodId:activePeriod?._id}),getAccountsApi(),getJournalsApi({periodId:activePeriod?._id,limit:30}),getControlRecsApi(activePeriod?._id)]);return {tb,accounts:accounts.accounts,journals:journals.journals,recs:recs.controlRecs};},[activePeriod?._id]);
  const [query,setQuery]=useState(''); const [view,setView]=useState('management'); const [closed,setClosed]=useState<string[]>([]);
  const [account,setAccount]=useState<string|null>(null); const [manual,setManual]=useState(false); const [evidence,setEvidence]=useState(false); const [rec,setRec]=useState<ControlRec|null>(null); const [journal,setJournal]=useState<JournalEntry|null>(null);
  const rows=(data?.tb.accounts || []).filter(a=>[a.code,a.name,a.department].join(' ').toLowerCase().includes(query.toLowerCase()));
  const groups=[{name:'Current Assets',test:(a:any)=>a.type==='asset'&&Number(a.code)<1500},{name:'Non-Current Assets',test:(a:any)=>a.type==='asset'&&Number(a.code)>=1500},...['liability','equity','revenue','expense'].map(type=>({name:({liability:'Liabilities',equity:'Equity',revenue:'Revenue',expense:'Expenses'} as Record<string,string>)[type],test:(a:any)=>a.type===type}))];
  return <div className="desk-page"><PageHeading eyebrow="General ledger & chart of accounts" title="Trial balance" description="A dealer-optimised chart of accounts with department, franchise and location dimensions built in. Every balance below drills through to the deal, repair order, invoice or VIN that created it." actions={<>{data&&<Tag tone={data.tb.isBalanced?'green':'red'}>{data.tb.isBalanced?'In balance':'Out of balance'}</Tag>}<Tag tone="gray">{data?.tb.dataSource === 'demo' ? 'Demo ledger · Read-only' : 'Management book'}</Tag></>}/>
  <div className="toolbar"><Tabs label="Book" value={view} onChange={setView} values={[{key:'management',label:'Management'},{key:'statutory',label:'Statutory',disabled:true},{key:'tax',label:'Tax',disabled:true},{key:'oem',label:'OEM-mapped',disabled:true}]}/><input className="search-input" aria-label="Search account, code or department" placeholder="⌕  Search account, code or department" value={query} onChange={e=>setQuery(e.target.value)}/></div>
  <LoadState loading={loading} error={error} retry={refresh}/>
  {!loading&&!error&&<div className="desk-columns"><div>{groups.map(group=>{const accounts=rows.filter(group.test);if(!accounts.length)return null;const collapsed=closed.includes(group.name);return <section key={group.name}><button className="account-group" onClick={()=>setClosed(old=>collapsed?old.filter(n=>n!==group.name):[...old,group.name])} aria-expanded={!collapsed}><span style={{color:'#999',marginRight:12}}>{collapsed?'›':'⌄'}</span><strong>{group.name}</strong><span className="num">{dollars(accounts.reduce((sum,a)=>sum+a.netDebitCents-a.netCreditCents,0))}</span></button>{!collapsed&&<div className="table-scroll"><table className="data-table" style={{borderTop:0}}><thead><tr><th>Acct</th><th>Account name</th><th>Dept</th><th className="num">Debit</th><th className="num">Credit</th></tr></thead><tbody>{accounts.map(a=><tr key={a.accountId}><td className="num" style={{color:'#858580',textAlign:'left'}}>{a.code}</td><td><button className="text-link" onClick={()=>setAccount(a.accountId)}>{a.name}</button></td><td className="department">{a.department}</td><td className="num">{a.netDebitCents?dollars(a.netDebitCents):'—'}</td><td className="num">{a.netCreditCents?dollars(a.netCreditCents):'—'}</td></tr>)}</tbody></table></div>}</section>;})}<LoadState loading={false} empty={!rows.length}/><div className="actions section-spacer"><button className="desk-button primary" disabled={data?.tb.dataSource === 'demo'} onClick={()=>setManual(true)}>Manual journal</button><button className="desk-button" onClick={()=>setEvidence(true)}>Export evidence pack</button></div><section className="side-section"><h3>Control reconciliations</h3>{data?.recs.map(r=><button key={r._id||r.type} className="summary-row w-full" onClick={()=>setRec(r)}><span>{r.type.replace(/_/g,' ')}</span><Tag tone={r.status==='completed'?'green':'amber'}>{r.status.replace(/_/g,' ')}</Tag></button>)}</section></div>
  <aside className="side-section" style={{marginTop:0}}><h3>Journal register · Real-time postings</h3>{data?.journals.map(j=><article key={j._id}><div className="toolbar"><button className="text-link num" onClick={()=>setJournal(j)}>{j.sourceRef || 'JE-'+j._id.slice(-6).toUpperCase()}</button><span className="num">{dollars(j.lines.reduce((s,l)=>s+l.debitCents,0))}</span></div><p className="department">{j.source.replace('_',' ')} · {new Date(j.date).toLocaleDateString('en-AU')}</p><p>{j.narration}</p><Tag tone={j.isReversal?'amber':'green'}>{j.isReversal?'Reversal':'Posted'}</Tag></article>)}{!data?.journals.length&&<p className="chart-note">No journal entries for this period.</p>}</aside></div>}
  <AccountDrillDrawer isOpen={!!account} onClose={()=>setAccount(null)} accountId={account} periodId={activePeriod?._id}/>
  <ManualJournalModal isOpen={manual} onClose={()=>setManual(false)} periodId={activePeriod?._id||''} accounts={data?.accounts||[]} onSuccess={refresh}/>
  <ControlRecModal isOpen={!!rec} onClose={()=>setRec(null)} rec={rec} periodId={activePeriod?._id} onSuccess={refresh}/>
  <EvidencePackModal isOpen={evidence} onClose={()=>setEvidence(false)} periodId={activePeriod?._id}/>
  <Modal isOpen={!!journal} onClose={()=>setJournal(null)} title={journal?.sourceRef||'Journal entry'} subtitle={journal?.narration} maxWidth="2xl"><table className="data-table"><thead><tr><th>Account</th><th>Department</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{journal?.lines.map((line,index)=>{const id=typeof line.accountId==='object'?line.accountId._id:line.accountId;return <tr key={index}><td><button className="text-link" onClick={()=>{setJournal(null);setAccount(id);}}>{data?.accounts.find(a=>a._id===id)?.name||id}</button></td><td>{line.department}</td><td className="num">{dollars(line.debitCents,2)}</td><td className="num">{dollars(line.creditCents,2)}</td></tr>;})}</tbody></table></Modal>
  </div>;
}
