import { useState } from 'react';
import { useResource } from '../../hooks/useResource';
import { allPages } from '../../api/pagination';
import { getVehiclesApi, getDealsApi, getFloorplanApi } from '../../api/inventory';
import { Vehicle, DealJacket } from '../../types/inventory';
import { PageHeading, Metrics, Eyebrow, Tabs, Tag, LoadState, compact, dollars } from '../../components/ui/Desk';
import { FacilityPanel } from './FacilityPanel';
import { VinCardModal } from './VinCardModal';
import { DealJacketModal } from './DealJacketModal';
import { AddCostLineModal } from './AddCostLineModal';
import { FloorplanModal } from './FloorplanModal';

export function InventoryPage() {
  const { data, loading, error, refresh } = useResource(async()=>{ const [vehicles,facility,deals]=await Promise.all([allPages<Vehicle>(async page=>{const r=await getVehiclesApi({page,limit:100});return {rows:r.vehicles,totalPages:r.totalPages};}),getFloorplanApi(),allPages<DealJacket>(async page=>{const r=await getDealsApi({page,limit:100});return {rows:r.deals,totalPages:r.totalPages};})]);return {vehicles,facility,deals}; });
  const [filter,setFilter]=useState('all'); const [query,setQuery]=useState(''); const [view,setView]=useState('vehicles');
  const [vehicle,setVehicle]=useState<Vehicle|null>(null); const [cost,setCost]=useState<Vehicle|null>(null); const [deal,setDeal]=useState<DealJacket|null>(null); const [floorplan,setFloorplan]=useState(false);
  const vehicles=data?.vehicles || [];
  const stock=vehicles.filter(v=>v.status!=='delivered');
  const age=(v:Vehicle)=>{const drawn=data?.facility.activeDraws.find(d=>(typeof d.vehicleId==='object'?d.vehicleId._id:d.vehicleId)===v._id)?.drawnDate;const date=drawn || v.createdAt;return date?Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/86400000)):null;};
  const bands=[{label:'0–30 days',min:0,max:30},{label:'31–60 days',min:31,max:60},{label:'61–90 days',min:61,max:90},{label:'91–120 days',min:91,max:120},{label:'120+ days',min:121,max:Infinity}];
  const visible=vehicles.filter(v=>(filter==='all'||v.class===filter)&&[v.stockNumber,v.vin,v.make,v.model].join(' ').toLowerCase().includes(query.toLowerCase()));
  const facility=data?.facility;
  return <div className="desk-page">
    <PageHeading eyebrow="Vehicle inventory accounting & floorplan management" title="VIN-level costing and floorplan sub-ledger" description="Every vehicle is a unique inventory item under specific identification. Cost accumulates by VIN and cost of sale is exact at the moment of delivery. Floorplan liability is always reconcilable to both the inventory schedule and the financier statement." actions={<button className="desk-button" onClick={()=>setFloorplan(true)}>View stocktake reconciliation</button>}/>
    <Metrics items={[{label:'Units in stock',value:data?stock.length:'—',note:'Across new, used and demonstrator'},{label:'Inventory at cost',value:data?compact(stock.reduce((s,v)=>s+v.totalCostCents,0)):'—',note:'New, used and demonstrator'},{label:'Floorplan drawn',value:facility?compact(facility.totalDrawnCents):'—',note:facility?'of '+compact(facility.facilityLimitCents)+' facility':'Facility balance'},{label:'Facility utilisation',value:facility&&facility.facilityLimitCents?`${(facility.totalDrawnCents/facility.facilityLimitCents*100).toFixed(1)}%`:'—',note:facility?compact(facility.headroomCents)+' headroom':'Available credit',tone:'amber'},{label:'Stock over 90 days',value:data?stock.filter(v=>(age(v)??0)>90).length:'—',note:'Review aging stock',tone:'amber'}]}/>
    <div className="section-heading"><Eyebrow>Days in stock</Eyebrow><h2>Aging heat map and forward interest cost</h2><p>The 91–120 day band is the decision point. If those units age one more band, forward interest cost rises materially and the curtailment calendar concentrates principal payments into a single fortnight.</p></div>
    <LoadState loading={loading} error={error} retry={refresh}/>
    <div className="heatmap">{bands.map((band,index)=>{const rows=stock.filter(v=>{const days=age(v);return days!==null&&days>=band.min&&days<=band.max;});const ids=new Set(rows.map(v=>v._id));const interest=facility?.activeDraws.filter(d=>ids.has(typeof d.vehicleId==='object'?d.vehicleId._id:d.vehicleId)).reduce((s,d)=>s+d.interestAccruedCents,0)||0;return <div key={band.label} style={{background:`rgba(174, 45, 35, ${index*.023})`}}><label>{band.label}</label><strong>{data?rows.length:'—'}</strong><small>units · {data?compact(rows.reduce((s,v)=>s+v.totalCostCents,0)):'—'}</small><div className="bar"><i style={{width:`${stock.length?rows.length/stock.length*100:0}%`}}/></div><small className="num">{data?dollars(interest):'—'} accrued interest</small></div>})}</div>
    <div className="desk-columns"><div><Tabs label="Class" values={['all','new','used','demo'].map(key=>({key,label:key}))} value={filter} onChange={setFilter}/><div className="table-scroll">{view==='vehicles'?<table className="data-table"><thead><tr><th>Stock / VIN</th><th>Description</th><th>Days</th><th>Cost</th><th>Floorplan</th><th>Accrued int.</th><th>Status</th></tr></thead><tbody>{visible.map(v=>{const draw=facility?.activeDraws.find(d=>(typeof d.vehicleId==='object'?d.vehicleId._id:d.vehicleId)===v._id);const days=age(v);return <tr key={v._id}><td><button className="text-link num" onClick={()=>setVehicle(v)}>{v.stockNumber}</button><small className="num">{v.vin}</small></td><td>{v.make} {v.model}<small>{v.year} · {v.class} · {v.variant}</small></td><td><Tag tone={days!==null&&days>90?'red':'gray'}>{days===null?'—':days+'d'}</Tag></td><td className="num">{dollars(v.totalCostCents)}</td><td className="num">{draw?dollars(draw.drawnAmountCents):'—'}</td><td className="num">{draw?dollars(draw.interestAccruedCents):'—'}</td><td style={{fontSize:10,color:'#858580'}}>{v.status.replace('_',' ')}</td></tr>})}</tbody></table>:<table className="data-table"><thead><tr><th>Deal</th><th>Delivery</th><th>Sale</th><th>Contribution</th></tr></thead><tbody>{data?.deals.map(d=><tr key={d._id}><td><button className="text-link" onClick={()=>setDeal(d)}>{d.dealNumber}</button></td><td>{new Date(d.deliveryDate).toLocaleDateString('en-AU')}</td><td className="num">{dollars(d.sellingPriceCents)}</td><td className="num">{dollars(d.dealContributionCents)}</td></tr>)}</tbody></table>}</div><LoadState loading={false} empty={!!data&&(view==='vehicles'?!visible.length:!data.deals.length)}/><div className="toolbar section-spacer"><input className="search-input" aria-label="Search stock or VIN" placeholder="Search stock, VIN or model…" value={query} onChange={e=>setQuery(e.target.value)}/><button className="desk-button" onClick={()=>setView(view==='vehicles'?'deals':'vehicles')}>{view==='vehicles'?'Delivered deal jackets':'Vehicle register'}</button></div><p className="chart-note">Aging uses the floorplan draw date where available, otherwise the inventory creation date. Interest shown is accrued to date; forward rates and curtailment schedules are not supplied.</p></div><FacilityPanel data={facility||null}/></div>
    <VinCardModal isOpen={!!vehicle} onClose={()=>setVehicle(null)} vehicle={vehicle} onOpenAddCostLine={v=>{setVehicle(null);setCost(v);}}/>
    <AddCostLineModal isOpen={!!cost} onClose={()=>setCost(null)} vehicle={cost} onSuccess={refresh}/>
    <DealJacketModal isOpen={!!deal} onClose={()=>setDeal(null)} deal={deal}/>
    <FloorplanModal isOpen={floorplan} onClose={()=>setFloorplan(false)}/>
  </div>;
}
