import { ReactNode } from 'react';
export function Eyebrow({ children }: { children: ReactNode }) { return <div className="eyebrow"><i>/</i> {children}</div>; }
export function PageHeading({ eyebrow, title, description, actions }: { eyebrow: string; title: string; description: string; actions?: ReactNode }) { return <header className="page-heading"><Eyebrow>{eyebrow}</Eyebrow><h1>{title}</h1><div className="heading-bottom"><p>{description}</p><div className="actions">{actions}</div></div></header>; }
export function Metrics({ items }: { items: { label: string; value: ReactNode; note: string; tone?: string }[] }) { return <div className="metrics" style={{ gridTemplateColumns: `repeat(${items.length}, minmax(0, 1fr))` }}>{items.map(item => <div key={item.label}><label>{item.label}</label><strong className={item.tone}>{item.value}</strong><small>{item.note}</small></div>)}</div>; }
export function Tag({ children, tone = 'blue' }: { children: ReactNode; tone?: string }) { return <span className={`desk-tag ${tone}`}>{children}</span>; }
export function Tabs({ label, values, value, onChange }: { label?: string; values: { key: string; label: string; disabled?: boolean }[]; value: string; onChange: (value: string) => void }) { return <div className="desk-tabs" role="tablist" aria-label={label || 'View'}>{label && <span>{label}</span>}{values.map(tab => <button key={tab.key} role="tab" aria-selected={value === tab.key} disabled={tab.disabled} className={value === tab.key ? 'selected' : ''} onClick={() => onChange(tab.key)}>{tab.label}</button>)}</div>; }
export function LoadState({ loading, error, empty, retry }: { loading: boolean; error?: string; empty?: boolean; retry?: () => void }) { if (!loading && !error && !empty) return null; return <div className="load-state" role={error ? 'alert' : 'status'}>{loading ? 'Loading records…' : error || 'No records found.'}{error && retry && <button onClick={retry}>Try again</button>}</div>; }
export const dollars = (cents: number, digits = 0) => new Intl.NumberFormat('en-AU', { style: 'currency', currency: 'AUD', minimumFractionDigits: digits, maximumFractionDigits: digits }).format(cents / 100);
export const compact = (cents: number) => Math.abs(cents) >= 100000000 ? `$${(cents / 100000000).toFixed(2)}m` : dollars(cents);
export function Confidence({ value }: { value?: number }) { const percent = value === undefined ? undefined : Math.round(value <= 1 ? value * 100 : value); return <span className={`confidence ${percent !== undefined && percent < 80 ? 'low' : ''}`}><i><b style={{ width: `${Math.min(100, Math.max(0, percent ?? 0))}%` }}/></i><small>{percent === undefined ? '—' : `${percent}%`}</small></span>; }

